packages:
  - "apps/*"
  - "packages/*"

catalog:
  react: ^19.2.0
  react-dom: ^19.2.0
  next: 16.2.0
  typescript: 5.9.2
  tailwindcss: ^4.3.0
  "@tailwindcss/postcss": ^4.3.0
  "@tailwindcss/cli": ^4.3.0
  ai: ^6.0.198
  "@ai-sdk/react": ^3.0.200
  "@mastra/ai-sdk": ^1.4.3
  "@mastra/client-js": ^1.23.2
  lucide-react: ^0.469.0
  eslint: ^9.39.1
  "@types/node": ^22.15.3
  "@types/react": 19.2.2
  "@types/react-dom": 19.2.2
